
# season start
SEASON_START: 2016-09-06

# list of teams
TEAMS: ['ARI', 'ATL','BAL','BUF','CAR','CHI','CIN','CLE','DAL','DEN','DET','GB','HOU','IND','JAX',
  'KC','LA','MIA','MIN','NE','NO','NYG','NYJ','OAK','PHI','PIT','SD','SEA','SF','TB','TEN','WAS']

# list of positions and quotas
POS: ['QB', 'RB', 'WR', 'TE', 'D', 'K']

LINEUP:
  QB : 1
  RB : 2
  WR : 3
  TE : 1
  D : 1
  K : 1

# total budget
BUDGET : 60000

# schedule
SCHEDULE_OPP:
  ARI : ["NE","TB","@BUF","LA","@SF","NYJ","SEA","@CAR","BYE","SF","@MIN","@ATL","WAS","@MIA","NO","@SEA","@LA"]
  ATL : ["TB","@OAK","@NO","CAR","@DEN","@SEA","SD","GB","@TB","@PHI","BYE","ARI","KC","@LA","SF","@CAR","NO"]
  BAL : ["BUF","@CLE","@JAX","OAK","WAS","@NYG","@NYJ","BYE","PIT","CLE","@DAL","CIN","MIA","@NE","PHI","@PIT","@CIN"]
  BUF : ["@BAL","NYJ","ARI","@NE","@LA","SF","@MIA","NE","@SEA","BYE","@CIN","JAX","@OAK","PIT","CLE","MIA","@NYJ"]
  CAR : ["@DEN","SF","MIN","@ATL","TB","@NO","BYE","ARI","@LA","KC","NO","@OAK","@SEA","SD","@WAS","ATL","@TB"]
  CHI : ["@HOU","PHI","@DAL","DET","@IND","JAX","@GB","MIN","BYE","@TB","@NYG","TEN","SF","@DET","GB","WAS","@MIN"]
  CIN : ["@NYJ","@PIT","DEN","MIA","@DAL","@NE","CLE","WAS","BYE","@NYG","BUF","@BAL","PHI","@CLE","PIT","@HOU","BAL"]
  CLE : ["@PHI","BAL","@MIA","@WAS","NE","@TEN","@CIN","NYJ","DAL","@BAL","PIT","NYG","BYE","CIN","@BUF","SD","@PIT"]
  DAL : ["NYG","@WAS","CHI","@SF","CIN","@GB","BYE","PHI","@CLE","@PIT","BAL","WAS","@MIN","@NYG","TB","DET","@PHI"]
  DEN : ["CAR","IND","@CIN","@TB","ATL","@SD","HOU","SD","@OAK","@NO","BYE","KC","@JAX","@TEN","NE","@KC","OAK"]
  DET : ["@IND","TEN","@GB","@CHI","PHI","LA","WAS","@HOU","@MIN","BYE","JAX","MIN","@NO","CHI","@NYG","@DAL","GB"]
  GB : ["@JAX","@MIN","DET","BYE","NYG","DAL","CHI","@ATL","IND","@TEN","@WAS","@PHI","HOU","SEA","@CHI","MIN","@DET"]
  HOU : ["CHI","KC","@NE","TEN","@MIN","IND","@DEN","DET","BYE","@JAX","OAK","SD","@GB","@IND","JAX","CIN","@TEN"]
  IND : ["DET","@DEN","SD","JAX","CHI","@HOU","@TEN","KC","@GB","BYE","TEN","PIT","@NYJ","HOU","@MIN","@OAK","JAX"]
  JAX : ["GB","@SD","BAL","IND","BYE","@CHI","OAK","@TEN","@KC","HOU","@DET","@BUF","DEN","MIN","@HOU","TEN","@IND"]
  KC : ["SD","@HOU","NYJ","@PIT","BYE","@OAK","NO","@IND","JAX","@CAR","TB","@DEN","@ATL","OAK","TEN","DEN","@SD"]
  LA : ["@SF","SEA","@TB","@ARI","BUF","@DET","NYG","BYE","CAR","@NYJ","MIA","@NO","@NE","ATL","@SEA","SF","ARI"]
  MIA : ["@SEA","@NE","CLE","@CIN","TEN","PIT","BUF","BYE","NYJ","@SD","@LA","SF","@BAL","ARI","@NYJ","@BUF","NE"]
  MIN : ["@TEN","GB","@CAR","NYG","HOU","BYE","@PHI","@CHI","DET","@WAS","ARI","@DET","DAL","@JAX","IND","@GB","CHI"]
  NE : ["@ARI","MIA","HOU","BUF","@CLE","CIN","@PIT","@BUF","BYE","SEA","@SF","@NYJ","LA","BAL","@DEN","NYJ","@MIA"]
  'NO' : ["OAK","@NYG","ATL","@SD","BYE","CAR","@KC","SEA","@SF","DEN","@CAR","LA","DET","@TB","@ARI","TB","@ATL"]
  NYG : ["@DAL","NO","WAS","@MIN","@GB","BAL","LA","BYE","PHI","CIN","CHI","@CLE","@PIT","DAL","DET","@PHI","@WAS"]
  NYJ : ["CIN","@BUF","@KC","SEA","@PIT","@ARI","BAL","@CLE","@MIA","LA","BYE","NE","IND","@SF","MIA","@NE","BUF"]
  OAK : ["@NO","ATL","@TEN","@BAL","SD","KC","@JAX","@TB","DEN","BYE","HOU","CAR","BUF","@KC","@SD","IND","@DEN"]
  PHI : ["CLE","@CHI","PIT","BYE","@DET","@WAS","MIN","@DAL","@NYG","ATL","@SEA","GB","@CIN","WAS","@BAL","NYG","DAL"]
  PIT : ["@WAS","CIN","@PHI","KC","NYJ","@MIA","NE","BYE","@BAL","DAL","@CLE","@IND","NYG","@BUF","@CIN","BAL","CLE"]
  SD : ["@KC","JAX","@IND","NO","@OAK","DEN","@ATL","@DEN","TEN","MIA","BYE","@HOU","TB","@CAR","OAK","@CLE","KC"]
  SEA : ["MIA","@LA","SF","@NYJ","BYE","ATL","@ARI","@NO","BUF","@NE","PHI","@TB","CAR","@GB","LA","ARI","@SF"]
  SF : ["LA","@CAR","@SEA","DAL","ARI","@BUF","TB","BYE","NO","@ARI","NE","@MIA","@CHI","NYJ","@ATL","@LA","SEA"]
  TB : ["@ATL","@ARI","LA","DEN","@CAR","BYE","@SF","OAK","ATL","CHI","@KC","SEA","@SD","NO","@DAL","@NO","CAR"]
  TEN : ["MIN","@DET","OAK","@HOU","@MIA","CLE","IND","JAX","@SD","GB","@IND","@CHI","BYE","DEN","@KC","@JAX","HOU"]
  WAS : ["PIT","DAL","@NYG","CLE","@BAL","PHI","@DET","CIN","BYE","MIN","GB","@DAL","@ARI","@PHI","CAR","@CHI","NYG"]

SCHEDULE_TIMES:
  ARI : ["SNF","SUN AFT","SUN 1PM","SUN AFT","THU","MNF","SNF","SUN AFT","BYE","SUN AFT","SUN 1PM","SUN 1PM","SUN AFT","SUN 1PM","SUN AFT","SAT","SUN AFT"]
  ATL : ["SUN 1PM","SUN AFT","MNF","SUN 1PM","SUN AFT","SUN AFT","SUN AFT","SUN 1PM","THU","SUN 1PM","BYE","SUN 1PM","SUN 1PM","SUN AFT","SUN AFT","SAT","SUN 1PM"]
  BAL : ["SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","BYE","SUN 1PM","THU","SUN 1PM","SUN 1PM","SUN 1PM","MNF","SUN 1PM","SUN AFT","SUN 1PM"]
  BUF : ["SUN 1PM","THU","SUN 1PM","SUN 1PM","SUN AFT","SUN 1PM","SUN 1PM","SUN 1PM","MNF","BYE","SUN 1PM","SUN 1PM","SUN AFT","SUN 1PM","SUN 1PM","SAT","SUN 1PM"]
  CAR : ["THU","SUN 1PM","SUN 1PM","SUN 1PM","MNF","SUN 1PM","BYE","SUN AFT","SUN AFT","SUN 1PM","THU","SUN AFT","SNF","SUN 1PM","MNF","SAT","SUN 1PM"]
  CHI : ["SUN 1PM","MNF","SNF","SUN 1PM","SUN 1PM","SUN 1PM","THU","MNF","BYE","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SAT","SUN 1PM"]
  CIN : ["SUN 1PM","SUN 1PM","SUN 1PM","THU","SUN AFT","SUN 1PM","SUN 1PM","INTL","BYE","MNF","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SNF","SAT","SUN 1PM"]
  CLE : ["SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","THU","SUN 1PM","SUN 1PM","BYE","SUN 1PM","SUN 1PM","SAT","SUN 1PM"]
  DAL : ["SUN AFT","SUN 1PM","SNF","SUN AFT","SUN AFT","SUN AFT","BYE","SNF","SUN 1PM","SUN AFT","SUN 1PM","THU","THU","SNF","SUN 1PM","MNF","SUN 1PM"]
  DEN : ["THU","SUN AFT","SUN 1PM","SUN AFT","SUN AFT","THU","MNF","SUN AFT","SNF","SUN 1PM","BYE","SUN AFT","SUN 1PM","SUN 1PM","SUN AFT","SNF","SUN AFT"]
  DET : ["SUN AFT","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","BYE","SUN 1PM","THU","SUN 1PM","SUN 1PM","SUN 1PM","MNF","SUN 1PM"]
  GB : ["SUN 1PM","SNF","SUN 1PM","BYE","SNF","SUN AFT","THU","SUN 1PM","SUN AFT","SUN 1PM","SNF","MNF","SUN 1PM","SUN AFT","SUN 1PM","SAT","SUN 1PM"]
  HOU : ["SUN 1PM","SUN 1PM","THU","SUN 1PM","SUN 1PM","SNF","MNF","SUN 1PM","BYE","SUN 1PM","MNF","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SAT","SUN 1PM"]
  IND : ["SUN AFT","SUN AFT","SUN AFT","INTL","SUN 1PM","SNF","SUN 1PM","SUN 1PM","SUN AFT","BYE","SUN 1PM","THU","MNF","SUN 1PM","SUN 1PM","SAT","SUN 1PM"]
  JAX : ["SUN 1PM","SUN AFT","SUN 1PM","INTL","BYE","SUN 1PM","SUN 1PM","THU","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SAT","SUN 1PM"]
  KC : ["SUN 1PM","SUN 1PM","SUN AFT","SNF","BYE","SUN AFT","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN AFT","SUN 1PM","THU","SUN 1PM","SNF","SUN AFT"]
  LA : ["MNF","SUN AFT","SUN AFT","SUN AFT","SUN AFT","SUN 1PM","INTL","BYE","SUN AFT","SUN 1PM","SUN AFT","SUN 1PM","SUN 1PM","SUN AFT","THU","SAT","SUN AFT"]
  MIA : ["SUN AFT","SUN 1PM","SUN 1PM","THU","SUN 1PM","SUN 1PM","SUN 1PM","BYE","SUN 1PM","SUN AFT","SUN AFT","SUN 1PM","SUN 1PM","SUN 1PM","SAT","SAT","SUN 1PM"]
  MIN : ["SUN 1PM","SNF","SUN 1PM","MNF","SUN 1PM","BYE","SUN 1PM","MNF","SUN 1PM","SUN 1PM","SUN 1PM","THU","THU","SUN 1PM","SUN 1PM","SAT","SUN 1PM"]
  NE : ["SNF","SUN 1PM","THU","SUN 1PM","SUN 1PM","SUN 1PM","SUN AFT","SUN 1PM","BYE","SNF","SUN AFT","SNF","SUN 1PM","MNF","SUN AFT","SAT","SUN 1PM"]
  'NO' : ["SUN 1PM","SUN 1PM","MNF","SUN AFT","BYE","SUN 1PM","SUN 1PM","SUN 1PM","SUN AFT","SUN 1PM","THU","SUN 1PM","SUN 1PM","SUN 1PM","SUN AFT","SAT","SUN 1PM"]
  NYG : ["SUN AFT","SUN 1PM","SUN 1PM","MNF","SNF","SUN 1PM","INTL","BYE","SUN 1PM","MNF","SUN 1PM","SUN 1PM","SUN AFT","SNF","SUN 1PM","THU","SUN 1PM"]
  NYJ : ["SUN 1PM","THU","SUN AFT","SUN 1PM","SUN 1PM","MNF","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","BYE","SNF","MNF","SUN AFT","SAT","SAT","SUN 1PM"]
  OAK : ["SUN 1PM","SUN AFT","SUN 1PM","SUN 1PM","SUN AFT","SUN AFT","SUN 1PM","SUN 1PM","SNF","BYE","MNF","SUN AFT","SUN AFT","THU","SUN AFT","SAT","SUN AFT"]
  PHI : ["SUN 1PM","MNF","SUN AFT","BYE","SUN 1PM","SUN 1PM","SUN 1PM","SNF","SUN 1PM","SUN 1PM","SUN AFT","MNF","SUN 1PM","SUN 1PM","SUN 1PM","THU","SUN 1PM"]
  PIT : ["MNF","SUN 1PM","SUN AFT","SNF","SUN 1PM","SUN 1PM","SUN AFT","BYE","SUN 1PM","SUN AFT","SUN 1PM","THU","SUN AFT","SUN 1PM","SNF","SUN AFT","SUN 1PM"]
  SD : ["SUN 1PM","SUN AFT","SUN AFT","SUN AFT","SUN AFT","THU","SUN AFT","SUN AFT","SUN AFT","SUN AFT","BYE","SUN 1PM","SUN AFT","SUN 1PM","SUN AFT","SAT","SUN AFT"]
  SEA : ["SUN AFT","SUN AFT","SUN AFT","SUN 1PM","BYE","SUN AFT","SNF","SUN 1PM","MNF","SNF","SUN AFT","SUN AFT","SNF","SUN AFT","THU","SAT","SUN AFT"]
  SF : ["MNF","SUN 1PM","SUN AFT","SUN AFT","THU","SUN 1PM","SUN AFT","BYE","SUN AFT","SUN AFT","SUN AFT","SUN 1PM","SUN 1PM","SUN AFT","SUN AFT","SAT","SUN AFT"]
  TB : ["SUN 1PM","SUN AFT","SUN AFT","SUN AFT","MNF","BYE","SUN AFT","SUN 1PM","THU","SUN 1PM","SUN 1PM","SUN AFT","SUN AFT","SUN 1PM","SUN 1PM","SAT","SUN 1PM"]
  TEN : ["SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","THU","SUN AFT","SUN 1PM","SUN 1PM","SUN 1PM","BYE","SUN 1PM","SUN 1PM","SAT","SUN 1PM"]
  WAS : ["MNF","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","SUN 1PM","INTL","BYE","SUN 1PM","SNF","THU","SUN AFT","SUN 1PM","MNF","SAT","SUN 1PM"]

# injury designations
INJ: ['GTD', 'OUT']

# where to store data
NF_DATA_URL: './data/nf'
NFL_API_DATA_URL: './data/nfl_api'

# where to store data
NF_TEAM_MAP:
  WSH: WAS
  JAC: JAX

# urls
NF_DAILY_FANTASY_URL: 'https://www.numberfire.com/nfl/daily-fantasy/daily-football-projections'
NF_REG_FANTASY_URL: 'https://www.numberfire.com/nfl/fantasy/fantasy-football-projections'
NFL_API_URL: 'http://api.fantasy.nfl.com/v1'
